### ISSUE TITLE
没有接口，该怎么去改，能不能换成全部用静态数据来实现，主要是我想先看效果

### ISSUE THREAD

**Issue by 9yues** [renmingliang/vue-lottery#1]
没有接口，该怎么去改，能不能换成全部用静态数据来实现，主要是我想先看效果

**Comment by renmingliang** [comment]
可以，我稍微修改下

**Comment by 9yues** [comment]
弄好了发一份到我邮箱谢谢，1538795093@qq.com

**Comment by renmingliang** [comment]
已增加mock模拟数据，可以直接git clone下来查看效果

**Comment by renmingliang** [comment]
@15521054523 已经增加mock模拟数据。可以直接git clone下来运行
